"""
Module 5: PrintFactory Job Configurator — Frappe-native engine
ZAZFIT / Athlettia LLC

Mixed-design nesting for POD: every Work Order is a unique custom garment.
Each garment has its own Seamly2D-generated DXF cut file.
This engine batches WOs that are ready to cut, submits them to PrintFactory
as a single nested cut job, and tracks the result.

Flow:
  1. WOs arrive at Cutting stage (tracker advances from Fabric Inspection)
  2. DXF files are generated by Seamly2D and stored in S3
  3. This engine groups WOs by fabric lot into batches
  4. PrintFactory receives: list of DXF S3 URLs + fabric dimensions
  5. PrintFactory nests all patterns, cuts, fires webhook
  6. Webhook triggers Cutting → Bundling advance on each WO's tracker

Nesting efficiency = fabric actually used / total fabric allocated.
Any batch below the configured threshold triggers a supervisor alert.
"""

import frappe
from frappe.utils import now_datetime


# Sentinel value for config fallback
_DEFAULTS = {
    "default_fabric_width_mm": 1500.0,
    "nesting_gap_mm": 5.0,
    "max_orders_per_batch": 20,
    "warn_below_efficiency_pct": 75.0,
    "dxf_s3_bucket": "",
    "dxf_s3_prefix": "dxf/",
}


def _get_config() -> dict:
    try:
        cfg = frappe.get_single("Print Job Config")
        return {
            "fabric_width_mm": cfg.default_fabric_width_mm or _DEFAULTS["default_fabric_width_mm"],
            "nesting_gap_mm": cfg.nesting_gap_mm or _DEFAULTS["nesting_gap_mm"],
            "max_orders_per_batch": cfg.max_orders_per_batch or _DEFAULTS["max_orders_per_batch"],
            "warn_below_efficiency_pct": cfg.warn_below_efficiency_pct or _DEFAULTS["warn_below_efficiency_pct"],
            "dxf_s3_bucket": cfg.dxf_s3_bucket or _DEFAULTS["dxf_s3_bucket"],
            "dxf_s3_prefix": cfg.dxf_s3_prefix or _DEFAULTS["dxf_s3_prefix"],
        }
    except Exception:
        return dict(_DEFAULTS)


class PrintJobConfigurator:
    """
    Orchestrates batching and submission of PrintFactory cut jobs.

    Usage:
        engine = PrintJobConfigurator()
        batches = engine.auto_batch_ready_orders()
        for batch_name in batches:
            engine.submit_batch(batch_name)
    """

    def __init__(self):
        self.cfg = _get_config()

    # ------------------------------------------------------------------
    # Auto-batching
    # ------------------------------------------------------------------

    def auto_batch_ready_orders(self) -> list:
        """
        Find all WOs at Cutting stage with a DXF file but no batch assigned.
        Groups by fabric lot. Creates PrintJobBatch docs (Draft).
        Returns list of batch doc names.
        """
        unbatched = self._get_unbatched_cutting_orders()
        if not unbatched:
            frappe.logger().info("ALICE PJC: No unbatched orders at Cutting stage.")
            return []

        # Group by fabric_lot
        by_lot = {}
        for row in unbatched:
            lot = row.get("fabric_lot") or "NO-LOT"
            by_lot.setdefault(lot, []).append(row)

        batch_names = []
        max_per_batch = int(self.cfg["max_orders_per_batch"])

        for lot, orders in by_lot.items():
            # Split into chunks of max_per_batch
            for chunk_start in range(0, len(orders), max_per_batch):
                chunk = orders[chunk_start: chunk_start + max_per_batch]
                batch = self._create_batch(lot, chunk)
                batch_names.append(batch.name)
                frappe.logger().info(
                    "ALICE PJC: Created batch {} — {} orders, fabric lot {}.".format(
                        batch.name, len(chunk), lot
                    )
                )

        return batch_names

    def submit_batch(self, batch_name: str, printfactory_client=None) -> dict:
        """
        Submit a Draft batch to PrintFactory.
        printfactory_client: an instance of alice_core PrintFactoryClient,
        or None to build the submission payload only (for testing).
        Returns the submission payload dict.
        """
        batch = frappe.get_doc("Print Job Batch", batch_name)
        if batch.status != "Draft":
            frappe.throw(
                frappe._("Batch {} is {} — only Draft batches can be submitted.".format(
                    batch_name, batch.status
                ))
            )

        dxf_urls = self._build_dxf_url_list(batch)
        if not dxf_urls:
            frappe.throw(
                frappe._("No DXF S3 keys found for batch {} — "
                         "ensure Seamly2D has exported cut files.".format(batch_name))
            )

        payload = {
            "batch": batch_name,
            "fabric_lot": batch.fabric_lot,
            "fabric_width_mm": batch.fabric_width_mm,
            "nesting_gap_mm": batch.nesting_gap_mm,
            "order_count": batch.order_count,
            "work_orders": [row.work_order for row in batch.work_orders],
            "dxf_files": dxf_urls,
        }

        if printfactory_client:
            try:
                job_id = printfactory_client.submit_nested_cut_job(
                    dxf_s3_urls=dxf_urls,
                    fabric_lot=batch.fabric_lot,
                    fabric_width_mm=batch.fabric_width_mm,
                    nesting_gap_mm=batch.nesting_gap_mm,
                    batch_ref=batch_name,
                )
                batch.on_submit_to_printfactory(job_id)
                payload["printfactory_job_id"] = job_id
                frappe.logger().info(
                    "ALICE PJC: Batch {} submitted — PrintFactory job {}.".format(
                        batch_name, job_id
                    )
                )
            except Exception as e:
                batch.on_printfactory_failed(str(e))
                frappe.logger().error(
                    "ALICE PJC: Batch {} submission failed — {}.".format(batch_name, e)
                )
                raise

        return payload

    # ------------------------------------------------------------------
    # Webhook handler
    # ------------------------------------------------------------------

    def handle_webhook(self, job_id: str, event: str,
                       efficiency_pct: float = None,
                       fabric_length_mm: float = None,
                       error_message: str = None):
        """
        Process incoming PrintFactory webhook event for a batch job.
        Called from the printfactory_webhook API endpoint.
        """
        batch_name = frappe.db.get_value(
            "Print Job Batch", {"printfactory_job_id": job_id}, "name"
        )
        if not batch_name:
            frappe.logger().warning(
                "ALICE PJC: Received webhook for unknown PrintFactory job {}.".format(job_id)
            )
            return

        batch = frappe.get_doc("Print Job Batch", batch_name)

        if event in ("completed", "job.completed"):
            batch.on_printfactory_complete(
                efficiency_pct=efficiency_pct,
                fabric_length_mm=fabric_length_mm,
            )
            # Advance each tracker: Cutting → Bundling
            self._advance_trackers_to_bundling(batch)

        elif event in ("failed", "job.failed"):
            batch.on_printfactory_failed(error_message or "PrintFactory reported failure.")

        else:
            frappe.logger().info(
                "ALICE PJC: Webhook event '{}' for job {} — no action needed.".format(
                    event, job_id
                )
            )

    def _advance_trackers_to_bundling(self, batch):
        """After print job completes, advance each WO tracker Cutting → Bundling."""
        for row in batch.work_orders:
            try:
                tracker_name = frappe.db.get_value(
                    "Production Stage Tracker",
                    {"work_order": row.work_order},
                    "name",
                )
                if not tracker_name:
                    continue
                tracker = frappe.get_doc("Production Stage Tracker", tracker_name)
                if tracker.current_stage == "Cutting":
                    tracker.set_stage(
                        stage="Bundling",
                        trigger_source="PrintFactory Webhook",
                        notes="Auto-advanced by PrintFactory job {} (batch {}).".format(
                            batch.printfactory_job_id, batch.name
                        ),
                    )
            except Exception as e:
                frappe.logger().error(
                    "ALICE PJC: Failed to advance tracker for WO {} — {}.".format(
                        row.work_order, e
                    )
                )

    # ------------------------------------------------------------------
    # Batch status sync
    # ------------------------------------------------------------------

    def sync_in_progress_batches(self, printfactory_client=None) -> list:
        """
        Called on ALICE startup. Checks PrintFactory for any jobs that
        completed while ALICE was offline and reconciles their batches.
        Returns list of batch names that were updated.
        """
        in_progress = frappe.get_all(
            "Print Job Batch",
            filters={"status": ["in", ["Submitted", "In Progress"]]},
            fields=["name", "printfactory_job_id"],
        )
        updated = []
        for b in in_progress:
            if not b.printfactory_job_id or not printfactory_client:
                continue
            try:
                job = printfactory_client.get_job_status(b.printfactory_job_id)
                status = (job.get("status") or "").lower()
                if status in ("completed", "done"):
                    self.handle_webhook(
                        job_id=b.printfactory_job_id,
                        event="completed",
                        efficiency_pct=job.get("nesting_efficiency_pct"),
                        fabric_length_mm=job.get("fabric_length_mm"),
                    )
                    updated.append(b.name)
                elif status in ("failed", "error"):
                    self.handle_webhook(
                        job_id=b.printfactory_job_id,
                        event="failed",
                        error_message=job.get("error_message", ""),
                    )
                    updated.append(b.name)
            except Exception as e:
                frappe.logger().error(
                    "ALICE PJC: Status sync failed for batch {} — {}.".format(b.name, e)
                )

        if updated:
            frappe.logger().info(
                "ALICE PJC: Startup sync — reconciled {} batches: {}.".format(
                    len(updated), updated
                )
            )
        return updated

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _get_unbatched_cutting_orders(self) -> list:
        """
        Return trackers at Cutting stage whose WO is not already in a Draft/Submitted batch.
        We check the Production Stage Tracker for DXF availability via pattern_file_ref.
        """
        return frappe.db.sql(
            """
            SELECT
                pst.name AS tracker,
                pst.work_order,
                pst.fabric_lot,
                pst.pattern_file_ref,
                pst.printfactory_job_id
            FROM `tabProduction Stage Tracker` pst
            WHERE pst.current_stage = 'Cutting'
              AND pst.is_complete = 0
              AND pst.pattern_file_ref IS NOT NULL
              AND pst.pattern_file_ref != ''
              AND NOT EXISTS (
                  SELECT 1
                  FROM `tabPrint Job Work Order` pjwo
                  JOIN `tabPrint Job Batch` pjb ON pjb.name = pjwo.parent
                  WHERE pjwo.work_order = pst.work_order
                    AND pjb.status IN ('Draft', 'Submitted', 'In Progress')
              )
            ORDER BY pst.stage_entered_at ASC
            """,
            as_dict=True,
        )

    def _create_batch(self, fabric_lot: str, orders: list):
        """Create and insert a Draft PrintJobBatch for the given orders."""
        batch = frappe.get_doc({
            "doctype": "Print Job Batch",
            "fabric_lot": fabric_lot,
            "status": "Draft",
            "fabric_width_mm": self.cfg["fabric_width_mm"],
            "nesting_gap_mm": self.cfg["nesting_gap_mm"],
        })
        for o in orders:
            dxf_key = self._build_dxf_key(o["work_order"])
            batch.append("work_orders", {
                "work_order": o["work_order"],
                "tracker": o["tracker"],
                "dxf_s3_key": dxf_key,
                "pattern_file_ref": o.get("pattern_file_ref") or "",
                "cut_status": "Queued",
            })
        batch.insert(ignore_permissions=True)
        frappe.db.commit()
        return batch

    def _build_dxf_key(self, work_order: str) -> str:
        prefix = self.cfg.get("dxf_s3_prefix", "dxf/")
        return "{}{}.dxf".format(prefix, work_order)

    def _build_dxf_url_list(self, batch) -> list:
        """Build S3 URLs for all DXF files in a batch."""
        bucket = self.cfg.get("dxf_s3_bucket", "")
        urls = []
        for row in batch.work_orders:
            if row.dxf_s3_key:
                if bucket:
                    urls.append("s3://{}/{}".format(bucket, row.dxf_s3_key))
                else:
                    urls.append(row.dxf_s3_key)
        return urls
